/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.12
 *
 * Project: 'AT32F421_IAP' 
 * Target:  'AT32F421_IAP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.5.2 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1


#endif /* PRE_INCLUDE_GLOBAL_H */
