/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.12
 *
 * Project: 'AT32F421_IAP' 
 * Target:  'AT32F421_IAP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "at32f421.h"

/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.5.4 */
#define __PERF_COUNTER__ 1


#endif /* RTE_COMPONENTS_H */
